GET http://localhost:10002/system/management/account/count
Accept: application/json

###

# ptrp 快捷键 快随生成一个post带参数的请求
POST http://localhost:10002/system/management/account/register
Content-Type: application/x-www-form-urlencoded

mobile=12444678031

###

POST http://localhost:10002/system/management/account/rendCode
Content-Type: application/x-www-form-urlencoded

mobile=13012345670

###

POST http://localhost:10002/system/management/account/login
Content-Type: application/x-www-form-urlencoded

mobile=13012345670&code=tref

###
