GET http://localhost:10001/system/management/account/name
Accept: application/json

###
GET http://localhost:10001/business/admin/business/test
Accept: application/json

###

POST http://localhost:10001/system/management/account/rendCode
Content-Type: application/json

{
  "mobile":"13012345680"
}


###
POST http://localhost:10001/system/management/account/login
Content-Type: application/json

{
  "mobile": "13012345671", "code": "p4v2"
}



> {%
    client.log(JSON.stringify(response.body));
    client.log(JSON.stringify(response.body.result.accessToken));
    client.global.set("accessToken",response.body.result.accessToken);
%}

###

POST http://localhost:10001/system/management/accountPassenger/save
Content-Type: application/json
accessToken: {{accessToken}}

{
  "name": "test111",
  "idCard": "123321",
  "phone": "13012345671",
  "type": "01"
}

###

# 修改乘客信息
POST http://localhost:10001/system/management/accountPassenger/save
Content-Type: application/json
accessToken: {{accessToken}}

{
  "id": "1652216014135496704",
  "name": "tes11t",
  "idCard": "123321111",
  "phone": "13012345671",
  "type": "01"
}
###

GET http://localhost:10001/system/management/accountPassenger/queryList?pageNum=1&pageSize=10
Content-Type: application/json
accessToken: {{accessToken}}

###

DELETE http://localhost:10001/system/management/accountPassenger/delete/1652218307891302400
Content-Type: application/json
accessToken: {{accessToken}}

###

# 车站接口调试
# 添加车站  新增与修改接口一样 参数不同
# 修改车站 需要添加该参数  "id": "1654440085342523392",
POST http://localhost:10001/business/admin/station/save
Content-Type: application/json

{

  "name": "重庆",
  "namePinyin": "chongqing",
  "namePy": "cq"
}

###

# 查询车站
GET http://localhost:10001/business/admin/station/queryList?pageNum=1&pageSize=10
Content-Type: application/json

###

# 删除车站
DELETE http://localhost:10001/business/admin/station/delete/1654438720721522688
Content-Type: application/json

###

# 车次接口调试
# 添加车次  新增与修改接口一样 参数不同
# 修改车次 需要添加该参数  "id": "1654443568581971968",
POST http://localhost:10001/business/admin/train/save
Content-Type: application/json

{
  "code": "D1",
  "type": "D",
  "start": "上海",
  "startPinyin": "shanghai",
  "startTime": "10:00:00",
  "end": "郑州",
  "endPinyin": "zhengzhou",
  "endTime": "14:00:00"
}

###

# 查询车次
GET http://localhost:10001/business/admin/train/queryList?pageNum=1&pageSize=10
Content-Type: application/json

###

# 删除车次
DELETE http://localhost:10001/business/admin/train/delete/1654443568581971968
Content-Type: application/json

###


# 火车两车站信息接口调试
# 添加火车两车站信息  新增与修改接口一样 参数不同
# 修改火车两车站信息 需要添加该参数  "id": "1654443568581971968",
POST http://localhost:10001/business/admin/trainStation/save
Content-Type: application/json

{
  "trainCode": "D1",
  "stationIndex": 4,
  "name": "郑州",
  "namePinyin": "zhengzhou",
  "inTime": "14:00:00",
  "outTime": "14:10:00",
  "stopTime": "00:10:00",
  "km": "100"
}

###

# 查询火车两车站信息
GET http://localhost:10001/business/admin/trainStation/queryList?pageNum=1&pageSize=10
Content-Type: application/json

###

# 删除火车两车站信息
DELETE http://localhost:10001/business/admin/trainStation/delete/1654446468234350592
Content-Type: application/json

###

# 火车车厢信息接口调试
# 添加火车车厢信息  新增与修改接口一样 参数不同
# 修改火车车厢信息 需要添加该参数  "id": "1654443568581971968",
POST http://localhost:10001/business/admin/trainCarriage/save
Content-Type: application/json

{
  "trainCode": "D1",
  "index": 6,
  "seatType": "01",
  "seatCount": 20,
  "rowCount": 5,
  "colCount": 4
}

###

# 查询火车车厢信息
GET http://localhost:10001/business/admin/trainCarriage/queryList?pageNum=1&pageSize=10
Content-Type: application/json

###

# 删除火车车厢信息
DELETE http://localhost:10001/business/admin/trainCarriage/delete/1654448398100729856
Content-Type: application/json

###











